### ISSUE TITLE
[需求]双色球中奖通知

### ISSUE THREAD

**Issue by q629988171** [nzai/lottery#1]
需求：输入购彩号码，每期彩票开奖完成后，通知中奖情况。

**Comment by nzai** [comment]
彩民一般都要自己比对中奖情况吧，自己买了彩票开奖后忙不得自己比对中奖情况的，要么批量投注，概率取胜，要么大户散财，没那点儿闲功夫，是哪种呢？如果要实现这个需求就要做用户系统了，还要记录投注情况，以及通知的微信邮件等等，短时间内是没这个时间精力来做，要不你提个PR？

**Comment by q629988171** [comment]
@nzai 

1. 批量投注和大户在实际操作过程中确实很难实现
2. 主要是针对个人（自己），固定一组号码，这样就不需要每次输入彩票号码
3. 倒不是忙的比对中奖情况，目的是减少买彩票整个流程（减少成本），可持续购彩（减少希望成本）
4. 购彩流程：选号、购彩、对彩、兑奖
5. 有这个功能后，我们只需要购彩就可以，剩下的就交给PYTHON
6. 其实已经做出来：https://github.com/q629988171/Double-color-ball-notice-after-winning-the-prize
